// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is the interface satisfied by both *pgxpool.Pool and pgx.Tx,
// allowing the same Queries struct to work inside or outside a transaction.
type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

// New creates a Queries instance backed by the given DBTX.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// Queries provides all the generated database access methods.
type Queries struct {
	db DBTX
}

// WithTx returns a copy of Queries bound to the given transaction.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
