// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import "context"

// Querier defines the interface for all generated query methods.
type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CountUsers(ctx context.Context) (int64, error)
	DeleteUser(ctx context.Context, id int32) (int64, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
